### ISSUE TITLE
🐛 [Plausible-CE] Clean install error

### ISSUE THREAD

**Issue by lucasbalena** [runtipi/runtipi-appstore#4612]
### Store Application

Plausible-CE

### App version

2.1.1

### Description

I don't know what is happening, maybe `conn.secret_key_base to be at least 64 bytes`

### Steps to reproduce

1. Install Plausible-CE
2. Try to open
3. Can't

### App logs

```bash
plausible-events-db  | ClickHouse Database directory appears to contain a database; Skipping initialization
plausible-events-db  | Processing configuration file '/etc/clickhouse-server/config.xml'.
plausible-events-db  | Merging configuration file '/etc/clickhouse-server/config.d/docker_related_config.xml'.
plausible-events-db  | Merging configuration file '/etc/clickhouse-server/config.d/logging.xml'.
plausible-events-db  | Logging warning to /var/log/clickhouse-server/clickhouse-server.log
plausible-events-db  | Logging errors to /var/log/clickhouse-server/clickhouse-server.err.log
plausible-events-db  | 2024.08.28 19:06:51.490387 [ 1 ] {}  Context: Linux is not using a fast clock source. Performance can be degraded. Check /sys/devices/system/clocksource/clocksource0/current_clocksource
plausible-events-db  | 2024.08.28 19:06:51.505075 [ 1 ] {}  Context: Linux threads max count is too low. Check /proc/sys/kernel/threads-max
plausible-events-db  | 2024.08.28 19:06:51.505598 [ 1 ] {}  Context: Delay accounting is not enabled, OSIOWaitMicroseconds will not be gathered. You can enable it using `echo 1 > /proc/sys/kernel/task_delayacct` or by using sysctl.
plausible-events-db  | 2024.08.28 19:06:51.505652 [ 1 ] {}  Context: Available memory at server startup is too low (2GiB).
plausible-events-db  | 2024.08.28 19:06:53.913180 [ 1 ] {}  Application: Disabling cgroup memory observer because of an error during initialization: Code: 107. DB::Exception: Cannot find cgroups v1 or v2 current memory file. (FILE_DOESNT_EXIST), Stack trace (when copying this message, always include the lines below):
plausible-events-db  |
plausible-events-db  | 0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000cbc851b
plausible-events-db  | 1. DB::Exception::Exception<>(int, FormatStringHelperImpl<>) @ 0x00000000076614c3
plausible-events-db  | 2. DB::CgroupsMemoryUsageObserver::CgroupsMemoryUsageObserver(std::chrono::duration>) @ 0x000000000cce452e
plausible-events-db  | 3. DB::Server::main(std::vector> const&) @ 0x000000000cd562bd
plausible-events-db  | 4. Poco::Util::Application::run() @ 0x0000000014ca8606
plausible-events-db  | 5. DB::Server::run() @ 0x000000000cd46671
plausible-events-db  | 6. Poco::Util::ServerApplication::run(int, char**) @ 0x0000000014cb14b9
plausible-events-db  | 7. mainEntryClickHouseServer(int, char**) @ 0x000000000cd4246a
plausible-events-db  | 8. main @ 0x0000000007651578
plausible-events-db  | 9. ? @ 0x0000783773e47083
plausible-events-db  | 10. _start @ 0x0000000005dee46e
plausible-events-db  |  (version 24.3.3.102 (official build))
plausible-db         |
plausible-db         | PostgreSQL Database directory appears to contain a database; Skipping initialization
plausible-db         |
plausible-db         | 2024-08-28 19:06:50.320 UTC [1] LOG:  starting PostgreSQL 16.4 on x86_64-pc-linux-musl, compiled by gcc (Alpine 13.2.1_git20240309) 13.2.1 20240309, 64-bit
plausible-db         | 2024-08-28 19:06:50.320 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
plausible-db         | 2024-08-28 19:06:50.321 UTC [1] LOG:  listening on IPv6 address "::", port 5432
plausible-db         | 2024-08-28 19:06:50.325 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
plausible-db         | 2024-08-28 19:06:50.338 UTC [27] LOG:  database system was shut down at 2024-08-28 19:06:42 UTC
plausible-db         | 2024-08-28 19:06:50.360 UTC [1] LOG:  database system is ready to accept connections
plausible-ce         | Loading plausible..
plausible-ce         | Starting dependencies..
plausible-ce         | Starting repos..
plausible-ce         | create Plausible.Repo database if it doesn't exist
plausible-events-db  | 2024.08.28 19:06:54.170707 [ 1 ] {}  Application: Listen [::]:9009 failed: Poco::Exception. Code: 1000, e.code() = 0, DNS error: EAI: Address family for hostname not supported (version 24.3.3.102 (official build)). If it is an IPv6 or IPv4 address and your host has disabled IPv6 or IPv4, then consider to specify not disabled IPv4 or IPv6 address to listen in  element of configuration file. Example for disabled IPv6: 0.0.0.0 . Example for disabled IPv4: ::
plausible-events-db  | 2024.08.28 19:06:54.957864 [ 1 ] {}  Application: Listen [::]:8123 failed: Poco::Exception. Code: 1000, e.code() = 0, DNS error: EAI: Address family for hostname not supported (version 24.3.3.102 (official build)). If it is an IPv6 or IPv4 address and your host has disabled IPv6 or IPv4, then consider to specify not disabled IPv4 or IPv6 address to listen in  element of configuration file. Example for disabled IPv6: 0.0.0.0 . Example for disabled IPv4: ::
plausible-events-db  | 2024.08.28 19:06:54.958030 [ 1 ] {}  Application: Listen [::]:9000 failed: Poco::Exception. Code: 1000, e.code() = 0, DNS error: EAI: Address family for hostname not supported (version 24.3.3.102 (official build)). If it is an IPv6 or IPv4 address and your host has disabled IPv6 or IPv4, then consider to specify not disabled IPv4 or IPv6 address to listen in  element of configuration file. Example for disabled IPv6: 0.0.0.0 . Example for disabled IPv4: ::
plausible-events-db  | 2024.08.28 19:06:54.958134 [ 1 ] {}  Application: Listen [::]:9004 failed: Poco::Exception. Code: 1000, e.code() = 0, DNS error: EAI: Address family for hostname not supported (version 24.3.3.102 (official build)). If it is an IPv6 or IPv4 address and your host has disabled IPv6 or IPv4, then consider to specify not disabled IPv4 or IPv6 address to listen in  element of configuration file. Example for disabled IPv6: 0.0.0.0 . Example for disabled IPv4: ::
plausible-events-db  | 2024.08.28 19:06:54.959322 [ 1 ] {}  Application: Listen [::]:9005 failed: Poco::Exception. Code: 1000, e.code() = 0, DNS error: EAI: Address family for hostname not supported (version 24.3.3.102 (official build)). If it is an IPv6 or IPv4 address and your host has disabled IPv6 or IPv4, then consider to specify not disabled IPv4 or IPv6 address to listen in  element of configuration file. Example for disabled IPv6: 0.0.0.0 . Example for disabled IPv4: ::
plausible-events-db  | 2024.08.28 19:07:02.378886 [ 49 ] {782015fb-24fc-4a56-b498-4bb854364562}  executeQuery: Code: 82. DB::Exception: Database plausible_events_db already exists. (DATABASE_ALREADY_EXISTS) (version 24.3.3.102 (official build)) (from 172.18.0.9:45412) (in query: CREATE DATABASE "plausible_events_db"), Stack trace (when copying this message, always include the lines below):
plausible-events-db  |
plausible-events-db  | 0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000cbc851b
plausible-events-db  | 1. DB::Exception::Exception(int, FormatStringHelperImpl::type>, String&) @ 0x000000000766ce63
plausible-events-db  | 2. DB::InterpreterCreateQuery::createDatabase(DB::ASTCreateQuery&) @ 0x0000000010b5e982
plausible-events-db  | 3. DB::InterpreterCreateQuery::execute() @ 0x0000000010b812be
plausible-events-db  | 4. DB::executeQueryImpl(char const*, char const*, std::shared_ptr, DB::QueryFlags, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) @ 0x000000001126e162
plausible-events-db  | 5. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::shared_ptr, std::function, DB::QueryFlags, std::optional const&, std::function) @ 0x000000001127341e
plausible-events-db  | 6. DB::HTTPHandler::processQuery(DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::optional&, StrongTypedef const&) @ 0x00000000122f0075
plausible-events-db  | 7. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&, StrongTypedef const&) @ 0x00000000122f4b34
plausible-events-db  | 8. DB::HTTPServerConnection::run() @ 0x00000000123740da
plausible-events-db  | 9. Poco::Net::TCPServerConnection::start() @ 0x0000000014c9b8d2
plausible-events-db  | 10. Poco::Net::TCPServerDispatcher::run() @ 0x0000000014c9c719
plausible-events-db  | 11. Poco::PooledThread::run() @ 0x0000000014d94e81
plausible-events-db  | 12. Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000014d9341d
plausible-events-db  | 13. ? @ 0x000078377401d609
plausible-events-db  | 14. ? @ 0x0000783773f42353
plausible-events-db  |
plausible-events-db  | 2024.08.28 19:07:02.381770 [ 49 ] {782015fb-24fc-4a56-b498-4bb854364562}  DynamicQueryHandler: Code: 82. DB::Exception: Database plausible_events_db already exists. (DATABASE_ALREADY_EXISTS), Stack trace (when copying this message, always include the lines below):
plausible-events-db  |
plausible-events-db  | 0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000cbc851b
plausible-events-db  | 1. DB::Exception::Exception(int, FormatStringHelperImpl::type>, String&) @ 0x000000000766ce63
plausible-events-db  | 2. DB::InterpreterCreateQuery::createDatabase(DB::ASTCreateQuery&) @ 0x0000000010b5e982
plausible-events-db  | 3. DB::InterpreterCreateQuery::execute() @ 0x0000000010b812be
plausible-events-db  | 4. DB::executeQueryImpl(char const*, char const*, std::shared_ptr, DB::QueryFlags, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) @ 0x000000001126e162
plausible-events-db  | 5. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::shared_ptr, std::function, DB::QueryFlags, std::optional const&, std::function) @ 0x000000001127341e
plausible-events-db  | 6. DB::HTTPHandler::processQuery(DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::optional&, StrongTypedef const&) @ 0x00000000122f0075
plausible-events-db  | 7. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&, StrongTypedef const&) @ 0x00000000122f4b34
plausible-events-db  | 8. DB::HTTPServerConnection::run() @ 0x00000000123740da
plausible-events-db  | 9. Poco::Net::TCPServerConnection::start() @ 0x0000000014c9b8d2
plausible-events-db  | 10. Poco::Net::TCPServerDispatcher::run() @ 0x0000000014c9c719
plausible-events-db  | 11. Poco::PooledThread::run() @ 0x0000000014d94e81
plausible-events-db  | 12. Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000014d9341d
plausible-events-db  | 13. ? @ 0x000078377401d609
plausible-events-db  | 14. ? @ 0x0000783773f42353
plausible-events-db  |  (version 24.3.3.102 (official build))
plausible-ce         | create Plausible.IngestRepo database if it doesn't exist
plausible-ce         | Creation of Db successful!
plausible-ce         | Loading plausible..
plausible-ce         | Starting dependencies..
plausible-ce         | Starting repos..
plausible-ce         | Running migrations for Elixir.Plausible.Repo
plausible-ce         | Running migrations for Elixir.Plausible.IngestRepo
plausible-ce         | Migrations successful!
plausible-ce         | 19:07:12.512 [error] [locus] [geolocation] database failed to load (:remote): {:http, 401, ~c"Unauthorized"}
plausible-ce         | 19:07:13.735 [error] [locus] [geolocation] database failed to load (:remote): {:http, 401, ~c"Unauthorized"}
plausible-ce         | 19:07:15.466 [error] [locus] [geolocation] database failed to load (:remote): {:http, 401, ~c"Unauthorized"}
plausible-ce         | 19:07:18.032 [error] [locus] [geolocation] database failed to load (:remote): {:http, 401, ~c"Unauthorized"}
plausible-ce         | 19:07:21.881 [error] [locus] [geolocation] database failed to load (:remote): {:http, 401, ~c"Unauthorized"}
plausible-ce         | 19:07:27.911 [error] [locus] [geolocation] database failed to load (:remote): {:http, 401, ~c"Unauthorized"}
plausible-ce         | 19:07:36.828 [error] [locus] [geolocation] database failed to load (:remote): {:http, 401, ~c"Unauthorized"}
plausible-ce         | 19:07:50.460 [error] [locus] [geolocation] database failed to load (:remote): {:http, 401, ~c"Unauthorized"}
plausible-ce         | 19:08:03.212 [error] #PID<0.4514.0> running PlausibleWeb.Endpoint (connection #PID<0.4513.0>, stream id 1) terminated
plausible-ce         | Request: GET /register
plausible-ce         | ** (exit) an exception was raised:
plausible-ce         |     ** (ArgumentError) cookie store expects conn.secret_key_base to be at least 64 bytes
plausible-ce         |         (plug 1.15.3) lib/plug/session/cookie.ex:184: Plug.Session.COOKIE.validate_secret_key_base/1
plausible-ce         |         (plug 1.15.3) lib/plug/session/cookie.ex:176: Plug.Session.COOKIE.derive/3
plausible-ce         |         (plug 1.15.3) lib/plug/session/cookie.ex:95: Plug.Session.COOKIE.put/4
plausible-ce         |         (plug 1.15.3) lib/plug/session.ex:96: anonymous fn/3 in Plug.Session.before_send/2
plausible-ce         |         (elixir 1.16.0) lib/enum.ex:2528: Enum."-reduce/3-lists^foldl/2-0-"/3
plausible-ce         |         (plug 1.15.3) lib/plug/conn.ex:1849: Plug.Conn.run_before_send/2
plausible-ce         |         (plug 1.15.3) lib/plug/conn.ex:441: Plug.Conn.send_resp/1
plausible-ce         |         (phoenix 1.7.10) lib/phoenix/router.ex:432: Phoenix.Router.__call__/5
plausible-ce         | 19:08:03.472 [error] #PID<0.4515.0> running PlausibleWeb.Endpoint (connection #PID<0.4513.0>, stream id 2) terminated
plausible-ce         | Request: GET /register
plausible-ce         | ** (exit) an exception was raised:
plausible-ce         |     ** (ArgumentError) cookie store expects conn.secret_key_base to be at least 64 bytes
plausible-ce         |         (plug 1.15.3) lib/plug/session/cookie.ex:184: Plug.Session.COOKIE.validate_secret_key_base/1
plausible-ce         |         (plug 1.15.3) lib/plug/session/cookie.ex:176: Plug.Session.COOKIE.derive/3
plausible-ce         |         (plug 1.15.3) lib/plug/session/cookie.ex:95: Plug.Session.COOKIE.put/4
plausible-ce         |         (plug 1.15.3) lib/plug/session.ex:96: anonymous fn/3 in Plug.Session.before_send/2
plausible-ce         |         (elixir 1.16.0) lib/enum.ex:2528: Enum."-reduce/3-lists^foldl/2-0-"/3
plausible-ce         |         (plug 1.15.3) lib/plug/conn.ex:1849: Plug.Conn.run_before_send/2
plausible-ce         |         (plug 1.15.3) lib/plug/conn.ex:441: Plug.Conn.send_resp/1
plausible-ce         |         (phoenix 1.7.10) lib/phoenix/router.ex:432: Phoenix.Router.__call__/5
plausible-ce         | 19:08:04.214 [error] #PID<0.4516.0> running PlausibleWeb.Endpoint (connection #PID<0.4513.0>, stream id 3) terminated
plausible-ce         | Request: GET /register
plausible-ce         | ** (exit) an exception was raised:
plausible-ce         |     ** (ArgumentError) cookie store expects conn.secret_key_base to be at least 64 bytes
plausible-ce         |         (plug 1.15.3) lib/plug/session/cookie.ex:184: Plug.Session.COOKIE.validate_secret_key_base/1
plausible-ce         |         (plug 1.15.3) lib/plug/session/cookie.ex:176: Plug.Session.COOKIE.derive/3
plausible-ce         |         (plug 1.15.3) lib/plug/session/cookie.ex:95: Plug.Session.COOKIE.put/4
plausible-ce         |         (plug 1.15.3) lib/plug/session.ex:96: anonymous fn/3 in Plug.Session.before_send/2
plausible-ce         |         (elixir 1.16.0) lib/enum.ex:2528: Enum."-reduce/3-lists^foldl/2-0-"/3
plausible-ce         |         (plug 1.15.3) lib/plug/conn.ex:1849: Plug.Conn.run_before_send/2
plausible-ce         |         (plug 1.15.3) lib/plug/conn.ex:441: Plug.Conn.send_resp/1
plausible-ce         |         (phoenix 1.7.10) lib/phoenix/router.ex:432: Phoenix.Router.__call__/5
plausible-ce         | 19:08:11.388 [error] [locus] [geolocation] database failed to load (:remote): {:http, 401, ~c"Unauthorized"}
```

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of RunTipi, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by JigSawFr** [comment]
Thanks for reporting, working on it

**Comment by Lancelot-Enguerrand** [comment]
Hello @lucasbalena,

I have changed the random generated "Base secret key" length to 64.
Plausible seems to work now (it still need a bit of time to start).
You just need to reinstall the app.

PS : I also added a healthcheck for consistency.
