### ISSUE TITLE
🐛 [Paperless-ngx] Broken as of 2.13.0 (working on 2.12.1)

### ISSUE THREAD

**Issue by profucius** [runtipi/runtipi-appstore#5375]
### Store Application

Paperless-ngx

### App version

2.13.0

### Description

I have this app installed as of 2.12.1 and it is working fine. However when updating it (within Runtipi) to the current latest version (2.13.0) the update succeeds, and the app seems to start, but the app's WebUI does not show anything but a blank screen. I checked the logs and found some errors. The app works again when I restore the backup to 2.12.1.

### Steps to reproduce

Update app to 2.13.0. Look at the logs.

### App logs

```bash
paperless-ngx  | Paperless-ngx docker container starting...
paperless-ngx  | Creating directory scratch directory /tmp/paperless
paperless-ngx  | Adjusting permissions of paperless files. This may take a while.
paperless-ngx  | Waiting for PostgreSQL to start...
paperless-ngx  | Connected to PostgreSQL
paperless-ngx  | Waiting for Redis...
paperless-ngx  | Connected to Redis broker.
paperless-ngx  | Apply database migrations...
paperless-ngx  | Traceback (most recent call last):
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/django/db/backends/base/base.py", line 279, in ensure_connection
paperless-ngx  |     self.connect()
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/django/utils/asyncio.py", line 26, in inner
paperless-ngx  |     return func(*args, **kwargs)
paperless-ngx  |            ^^^^^^^^^^^^^^^^^^^^^
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/django/db/backends/base/base.py", line 256, in connect
paperless-ngx  |     self.connection = self.get_new_connection(conn_params)
paperless-ngx  |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/django/utils/asyncio.py", line 26, in inner
paperless-ngx  |     return func(*args, **kwargs)
paperless-ngx  |            ^^^^^^^^^^^^^^^^^^^^^
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/django/db/backends/postgresql/base.py", line 332, in get_new_connection
paperless-ngx  |     connection = self.Database.connect(**conn_params)
paperless-ngx  |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/psycopg/connection.py", line 98, in connect
paperless-ngx  |     attempts = conninfo_attempts(params)
paperless-ngx  |                ^^^^^^^^^^^^^^^^^^^^^^^^^
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/psycopg/_conninfo_attempts.py", line 50, in conninfo_attempts
paperless-ngx  |     raise e.OperationalError(str(last_exc))
paperless-ngx  | psycopg.OperationalError: [Errno -2] Name or service not known
paperless-ngx  |
paperless-ngx  | The above exception was the direct cause of the following exception:
paperless-ngx  |
paperless-ngx  | Traceback (most recent call last):
paperless-ngx  |   File "/usr/src/paperless/src/manage.py", line 10, in 
paperless-ngx  |     execute_from_command_line(sys.argv)
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
paperless-ngx  |     utility.execute()
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/django/core/management/__init__.py", line 436, in execute
paperless-ngx  |     self.fetch_command(subcommand).run_from_argv(self.argv)
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/django/core/management/base.py", line 413, in run_from_argv
paperless-ngx  |     self.execute(*args, **cmd_options)
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/django/core/management/base.py", line 459, in execute
paperless-ngx  |     output = self.handle(*args, **options)
paperless-ngx  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/django/core/management/base.py", line 107, in wrapper
paperless-ngx  |     res = handle_func(*args, **kwargs)
paperless-ngx  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/django/core/management/commands/migrate.py", line 118, in handle
paperless-ngx  |     executor = MigrationExecutor(connection, self.migration_progress_callback)
paperless-ngx  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/django/db/migrations/executor.py", line 18, in __init__
paperless-ngx  |     self.loader = MigrationLoader(self.connection)
paperless-ngx  |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/django/db/migrations/loader.py", line 58, in __init__
paperless-ngx  |     self.build_graph()
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/django/db/migrations/loader.py", line 235, in build_graph
paperless-ngx  |     self.applied_migrations = recorder.applied_migrations()
paperless-ngx  |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/django/db/migrations/recorder.py", line 89, in applied_migrations
paperless-ngx  |     if self.has_table():
paperless-ngx  |        ^^^^^^^^^^^^^^^^
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/django/db/migrations/recorder.py", line 63, in has_table
paperless-ngx  |     with self.connection.cursor() as cursor:
paperless-ngx  |          ^^^^^^^^^^^^^^^^^^^^^^^^
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/django/utils/asyncio.py", line 26, in inner
paperless-ngx  |     return func(*args, **kwargs)
paperless-ngx  |            ^^^^^^^^^^^^^^^^^^^^^
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/django/db/backends/base/base.py", line 320, in cursor
paperless-ngx  |     return self._cursor()
paperless-ngx  |            ^^^^^^^^^^^^^^
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/django/db/backends/base/base.py", line 296, in _cursor
paperless-ngx  |     self.ensure_connection()
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/django/utils/asyncio.py", line 26, in inner
paperless-ngx  |     return func(*args, **kwargs)
paperless-ngx  |            ^^^^^^^^^^^^^^^^^^^^^
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/django/db/backends/base/base.py", line 278, in ensure_connection
paperless-ngx  |     with self.wrap_database_errors:
paperless-ngx  |          ^^^^^^^^^^^^^^^^^^^^^^^^^
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
paperless-ngx  |     raise dj_exc_value.with_traceback(traceback) from exc_value
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/django/db/backends/base/base.py", line 279, in ensure_connection
paperless-ngx  |     self.connect()
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/django/utils/asyncio.py", line 26, in inner
paperless-ngx  |     return func(*args, **kwargs)
paperless-ngx  |            ^^^^^^^^^^^^^^^^^^^^^
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/django/db/backends/base/base.py", line 256, in connect
paperless-ngx  |     self.connection = self.get_new_connection(conn_params)
paperless-ngx  |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/django/utils/asyncio.py", line 26, in inner
paperless-ngx  |     return func(*args, **kwargs)
paperless-ngx  |            ^^^^^^^^^^^^^^^^^^^^^
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/django/db/backends/postgresql/base.py", line 332, in get_new_connection
paperless-ngx  |     connection = self.Database.connect(**conn_params)
paperless-ngx  |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/psycopg/connection.py", line 98, in connect
paperless-ngx  |     attempts = conninfo_attempts(params)
paperless-ngx  |                ^^^^^^^^^^^^^^^^^^^^^^^^^
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/psycopg/_conninfo_attempts.py", line 50, in conninfo_attempts
paperless-ngx  |     raise e.OperationalError(str(last_exc))
paperless-ngx  | django.db.utils.OperationalError: [Errno -2] Name or service not known
paperless-ngx  | Paperless-ngx docker container starting...
paperless-ngx  | Creating directory scratch directory /tmp/paperless
paperless-ngx  | Adjusting permissions of paperless files. This may take a while.
paperless-ngx  | Waiting for PostgreSQL to start...
paperless-ngx  | Connected to PostgreSQL
paperless-ngx  | Waiting for Redis...
paperless-ngx  | Connected to Redis broker.
paperless-ngx  | Apply database migrations...
paperless-ngx  | Traceback (most recent call last):
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/django/db/backends/base/base.py", line 279, in ensure_connection
paperless-ngx  |     self.connect()
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/django/utils/asyncio.py", line 26, in inner
paperless-ngx  |     return func(*args, **kwargs)
paperless-ngx  |            ^^^^^^^^^^^^^^^^^^^^^
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/django/db/backends/base/base.py", line 256, in connect
paperless-ngx  |     self.connection = self.get_new_connection(conn_params)
paperless-ngx  |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/django/utils/asyncio.py", line 26, in inner
paperless-ngx  |     return func(*args, **kwargs)
paperless-ngx  |            ^^^^^^^^^^^^^^^^^^^^^
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/django/db/backends/postgresql/base.py", line 332, in get_new_connection
paperless-ngx  |     connection = self.Database.connect(**conn_params)
paperless-ngx  |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/psycopg/connection.py", line 98, in connect
paperless-ngx  |     attempts = conninfo_attempts(params)
paperless-ngx  |                ^^^^^^^^^^^^^^^^^^^^^^^^^
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/psycopg/_conninfo_attempts.py", line 50, in conninfo_attempts
paperless-ngx  |     raise e.OperationalError(str(last_exc))
paperless-ngx  | psycopg.OperationalError: [Errno -2] Name or service not known
paperless-ngx  |
paperless-ngx  | The above exception was the direct cause of the following exception:
paperless-ngx  |
paperless-ngx  | Traceback (most recent call last):
paperless-ngx  |   File "/usr/src/paperless/src/manage.py", line 10, in 
paperless-ngx  |     execute_from_command_line(sys.argv)
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
paperless-ngx  |     utility.execute()
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/django/core/management/__init__.py", line 436, in execute
paperless-ngx  |     self.fetch_command(subcommand).run_from_argv(self.argv)
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/django/core/management/base.py", line 413, in run_from_argv
paperless-ngx  |     self.execute(*args, **cmd_options)
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/django/core/management/base.py", line 459, in execute
paperless-ngx  |     output = self.handle(*args, **options)
paperless-ngx  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/django/core/management/base.py", line 107, in wrapper
paperless-ngx  |     res = handle_func(*args, **kwargs)
paperless-ngx  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/django/core/management/commands/migrate.py", line 118, in handle
paperless-ngx  |     executor = MigrationExecutor(connection, self.migration_progress_callback)
paperless-ngx  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/django/db/migrations/executor.py", line 18, in __init__
paperless-ngx  |     self.loader = MigrationLoader(self.connection)
paperless-ngx  |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/django/db/migrations/loader.py", line 58, in __init__
paperless-ngx  |     self.build_graph()
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/django/db/migrations/loader.py", line 235, in build_graph
paperless-ngx  |     self.applied_migrations = recorder.applied_migrations()
paperless-ngx  |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/django/db/migrations/recorder.py", line 89, in applied_migrations
paperless-ngx  |     if self.has_table():
paperless-ngx  |        ^^^^^^^^^^^^^^^^
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/django/db/migrations/recorder.py", line 63, in has_table
paperless-ngx  |     with self.connection.cursor() as cursor:
paperless-ngx  |          ^^^^^^^^^^^^^^^^^^^^^^^^
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/django/utils/asyncio.py", line 26, in inner
paperless-ngx  |     return func(*args, **kwargs)
paperless-ngx  |            ^^^^^^^^^^^^^^^^^^^^^
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/django/db/backends/base/base.py", line 320, in cursor
paperless-ngx  |     return self._cursor()
paperless-ngx  |            ^^^^^^^^^^^^^^
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/django/db/backends/base/base.py", line 296, in _cursor
paperless-ngx  |     self.ensure_connection()
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/django/utils/asyncio.py", line 26, in inner
paperless-ngx  |     return func(*args, **kwargs)
paperless-ngx  |            ^^^^^^^^^^^^^^^^^^^^^
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/django/db/backends/base/base.py", line 278, in ensure_connection
paperless-ngx  |     with self.wrap_database_errors:
paperless-ngx  |          ^^^^^^^^^^^^^^^^^^^^^^^^^
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
paperless-ngx  |     raise dj_exc_value.with_traceback(traceback) from exc_value
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/django/db/backends/base/base.py", line 279, in ensure_connection
paperless-ngx  |     self.connect()
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/django/utils/asyncio.py", line 26, in inner
paperless-ngx  |     return func(*args, **kwargs)
paperless-ngx  |            ^^^^^^^^^^^^^^^^^^^^^
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/django/db/backends/base/base.py", line 256, in connect
paperless-ngx  |     self.connection = self.get_new_connection(conn_params)
paperless-ngx  |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/django/utils/asyncio.py", line 26, in inner
paperless-ngx  |     return func(*args, **kwargs)
paperless-ngx  |            ^^^^^^^^^^^^^^^^^^^^^
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/django/db/backends/postgresql/base.py", line 332, in get_new_connection
paperless-ngx  |     connection = self.Database.connect(**conn_params)
paperless-ngx  |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/psycopg/connection.py", line 98, in connect
paperless-ngx  |     attempts = conninfo_attempts(params)
paperless-ngx  |                ^^^^^^^^^^^^^^^^^^^^^^^^^
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/psycopg/_conninfo_attempts.py", line 50, in conninfo_attempts
paperless-ngx  |     raise e.OperationalError(str(last_exc))
paperless-ngx  | django.db.utils.OperationalError: [Errno -2] Name or service not known
paperless-ngx  | Paperless-ngx docker container starting...
paperless-ngx  | Creating directory scratch directory /tmp/paperless
paperless-ngx  | Adjusting permissions of paperless files. This may take a while.
paperless-ngx  | Waiting for PostgreSQL to start...
paperless-ngx  | Connected to PostgreSQL
paperless-ngx  | Waiting for Redis...
paperless-ngx  | Connected to Redis broker.
paperless-ngx  | Apply database migrations...
paperless-ngx  | Traceback (most recent call last):
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/django/db/backends/base/base.py", line 279, in ensure_connection
paperless-ngx  |     self.connect()
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/django/utils/asyncio.py", line 26, in inner
paperless-ngx  |     return func(*args, **kwargs)
paperless-ngx  |            ^^^^^^^^^^^^^^^^^^^^^
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/django/db/backends/base/base.py", line 256, in connect
paperless-ngx  |     self.connection = self.get_new_connection(conn_params)
paperless-ngx  |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/django/utils/asyncio.py", line 26, in inner
paperless-ngx  |     return func(*args, **kwargs)
paperless-ngx  |            ^^^^^^^^^^^^^^^^^^^^^
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/django/db/backends/postgresql/base.py", line 332, in get_new_connection
paperless-ngx  |     connection = self.Database.connect(**conn_params)
paperless-ngx  |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/psycopg/connection.py", line 98, in connect
paperless-ngx  |     attempts = conninfo_attempts(params)
paperless-ngx  |                ^^^^^^^^^^^^^^^^^^^^^^^^^
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/psycopg/_conninfo_attempts.py", line 50, in conninfo_attempts
paperless-ngx  |     raise e.OperationalError(str(last_exc))
paperless-ngx  | psycopg.OperationalError: [Errno -2] Name or service not known
paperless-ngx  |
paperless-ngx  | The above exception was the direct cause of the following exception:
paperless-ngx  |
paperless-ngx  | Traceback (most recent call last):
paperless-ngx  |   File "/usr/src/paperless/src/manage.py", line 10, in 
paperless-ngx  |     execute_from_command_line(sys.argv)
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
paperless-ngx  |     utility.execute()
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/django/core/management/__init__.py", line 436, in execute
paperless-ngx  |     self.fetch_command(subcommand).run_from_argv(self.argv)
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/django/core/management/base.py", line 413, in run_from_argv
paperless-ngx  |     self.execute(*args, **cmd_options)
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/django/core/management/base.py", line 459, in execute
paperless-ngx  |     output = self.handle(*args, **options)
paperless-ngx  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/django/core/management/base.py", line 107, in wrapper
paperless-ngx  |     res = handle_func(*args, **kwargs)
paperless-ngx  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/django/core/management/commands/migrate.py", line 118, in handle
paperless-ngx  |     executor = MigrationExecutor(connection, self.migration_progress_callback)
paperless-ngx  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/django/db/migrations/executor.py", line 18, in __init__
paperless-ngx  |     self.loader = MigrationLoader(self.connection)
paperless-ngx  |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/django/db/migrations/loader.py", line 58, in __init__
paperless-ngx  |     self.build_graph()
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/django/db/migrations/loader.py", line 235, in build_graph
paperless-ngx  |     self.applied_migrations = recorder.applied_migrations()
paperless-ngx  |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/django/db/migrations/recorder.py", line 89, in applied_migrations
paperless-ngx  |     if self.has_table():
paperless-ngx  |        ^^^^^^^^^^^^^^^^
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/django/db/migrations/recorder.py", line 63, in has_table
paperless-ngx  |     with self.connection.cursor() as cursor:
paperless-ngx  |          ^^^^^^^^^^^^^^^^^^^^^^^^
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/django/utils/asyncio.py", line 26, in inner
paperless-ngx  |     return func(*args, **kwargs)
paperless-ngx  |            ^^^^^^^^^^^^^^^^^^^^^
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/django/db/backends/base/base.py", line 320, in cursor
paperless-ngx  |     return self._cursor()
paperless-ngx  |            ^^^^^^^^^^^^^^
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/django/db/backends/base/base.py", line 296, in _cursor
paperless-ngx  |     self.ensure_connection()
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/django/utils/asyncio.py", line 26, in inner
paperless-ngx  |     return func(*args, **kwargs)
paperless-ngx  |            ^^^^^^^^^^^^^^^^^^^^^
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/django/db/backends/base/base.py", line 278, in ensure_connection
paperless-ngx  |     with self.wrap_database_errors:
paperless-ngx  |          ^^^^^^^^^^^^^^^^^^^^^^^^^
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
paperless-ngx  |     raise dj_exc_value.with_traceback(traceback) from exc_value
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/django/db/backends/base/base.py", line 279, in ensure_connection
paperless-ngx  |     self.connect()
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/django/utils/asyncio.py", line 26, in inner
paperless-ngx  |     return func(*args, **kwargs)
paperless-ngx  |            ^^^^^^^^^^^^^^^^^^^^^
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/django/db/backends/base/base.py", line 256, in connect
paperless-ngx  |     self.connection = self.get_new_connection(conn_params)
paperless-ngx  |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/django/utils/asyncio.py", line 26, in inner
paperless-ngx  |     return func(*args, **kwargs)
paperless-ngx  |            ^^^^^^^^^^^^^^^^^^^^^
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/django/db/backends/postgresql/base.py", line 332, in get_new_connection
paperless-ngx  |     connection = self.Database.connect(**conn_params)
paperless-ngx  |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/psycopg/connection.py", line 98, in connect
paperless-ngx  |     attempts = conninfo_attempts(params)
paperless-ngx  |                ^^^^^^^^^^^^^^^^^^^^^^^^^
paperless-ngx  |   File "/usr/local/lib/python3.12/site-packages/psycopg/_conninfo_attempts.py", line 50, in conninfo_attempts
paperless-ngx  |     raise e.OperationalError(str(last_exc))
paperless-ngx  | django.db.utils.OperationalError: [Errno -2] Name or service not known
paperless-ngx - Tipi
```

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of RunTipi, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by profucius** [comment]
Bump. This is still an issue.

**Comment by profucius** [comment]
Update: This is happening to almost every app that has been updated since Runtipi switched away from Docker Compose. I have more than a handful of apps that I've tested manually and fail to launch after the update, but rolling back to a backup they work fine.

Please assist in discovering the issue so that this can be resolved. It is mentally taxing and insecure to leave updates available while ignoring them.

**Comment by profucius** [comment]
I saw there was an update for this app (v2.13.4) and decided to try it. I was still unable to access the WebUI after updating.

I was able to resolve the issue by uninstalling, which deleted the app data, and reinstalling fresh. However, this is not an acceptable solution, as having data stored in the app is not easily replaceable once the user starts uploading documents to the database.

Can someone please take a look at my OP and help determine why this issue arose in the first place?

**Comment by meienberger** [comment]
Hello @profucius sorry for the late reply, I'll have a look asap

**Comment by WoOS2** [comment]
OK, after reading a bit about it (see e.g. https://github.com/paperless-ngx/paperless-ngx/discussions/6669) a postgress update seems to be a major pain in the a**.
May I suggest to simply go back to postgress:16 as there seems to be no need for version 17 for paperless ngx.
